services:
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  cache:
    image: redis
    ports:
      - "6379:6379"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - database
