/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      "characters",
      [
        {
          id: 1,
          name: "Rick Sanchez",
          status: "Alive",
          species: "Human",
          gender: "Male",
          origin: "Earth (C-137)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
          createdAt: new Date("2017-11-04T18:48:46.250Z"),
        },
        {
          id: 2,
          name: "Morty Smith",
          status: "Alive",
          species: "Human",
          gender: "Male",
          origin: "unknown",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
          createdAt: new Date("2017-11-04T18:50:21.651Z"),
        },
        {
          id: 3,
          name: "Summer Smith",
          status: "Alive",
          species: "Human",
          gender: "Female",
          origin: "Earth (Replacement Dimension)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
          createdAt: new Date("2017-11-04T19:09:56.428Z"),
        },
        {
          id: 4,
          name: "Beth Smith",
          status: "Alive",
          species: "Human",
          gender: "Female",
          origin: "Earth (Replacement Dimension)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
          createdAt: new Date("2017-11-04T19:22:43.665Z"),
        },
        {
          id: 5,
          name: "Jerry Smith",
          status: "Alive",
          species: "Human",
          gender: "Male",
          origin: "Earth (Replacement Dimension)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/5.jpeg",
          createdAt: new Date("2017-11-04T19:26:56.301Z"),
        },
        {
          id: 6,
          name: "Birdperson",
          status: "Alive",
          species: "Birdperson",
          gender: "Male",
          origin: "Bird World",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/6.jpeg",
          createdAt: new Date("2017-11-04T18:47:39.664Z"),
        },
        {
          id: 7,
          name: "Squanchy",
          status: "Alive",
          species: "Catperson",
          gender: "Male",
          origin: "Squanch Planet",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
          createdAt: new Date("2017-11-04T18:44:28.565Z"),
        },
        {
          id: 8,
          name: "Evil Morty",
          status: "Alive",
          species: "Human",
          gender: "Male",
          origin: "Earth (C-137)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
          createdAt: new Date("2017-11-04T18:48:21.698Z"),
        },
        {
          id: 9,
          name: "Mr. Poopybutthole",
          status: "Alive",
          species: "Human",
          gender: "Male",
          origin: "unknown",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/9.jpeg",
          createdAt: new Date("2017-11-04T18:47:13.937Z"),
        },
        {
          id: 10,
          name: "Tina",
          status: "Alive",
          species: "Human",
          gender: "Female",
          origin: "Earth (C-137)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/10.jpeg",
          createdAt: new Date("2017-11-04T18:46:47.678Z"),
        },
        {
          id: 11,
          name: "Kyle",
          status: "Alive",
          species: "Human",
          gender: "Male",
          origin: "Earth (C-137)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/11.jpeg",
          createdAt: new Date("2017-11-04T18:46:19.541Z"),
        },
        {
          id: 12,
          name: "Doofus Rick",
          status: "Alive",
          species: "Human",
          gender: "Male",
          origin: "Earth (C-137)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/12.jpeg",
          createdAt: new Date("2017-11-04T18:45:52.579Z"),
        },
        {
          id: 13,
          name: "Principal Vagina",
          status: "Alive",
          species: "Human",
          gender: "Male",
          origin: "Earth (C-137)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/13.jpeg",
          createdAt: new Date("2017-11-04T18:45:27.415Z"),
        },
        {
          id: 14,
          name: "Jessica",
          status: "Alive",
          species: "Human",
          gender: "Female",
          origin: "Earth (C-137)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/14.jpeg",
          createdAt: new Date("2017-11-04T18:44:57.717Z"),
        },
        {
          id: 15,
          name: "Nancy",
          status: "Alive",
          species: "Human",
          gender: "Female",
          origin: "Earth (C-137)",
          imageUrl: "https://rickandmortyapi.com/api/character/avatar/15.jpeg",
          createdAt: new Date("2017-11-04T18:44:06.628Z"),
        },
      ],
      {},
    );
    await queryInterface.bulkInsert(
      "comments",
      [
        {
          characterId: 1,
          text: "Wubba Lubba Dub-Dub!",
          createdAt: new Date(),
        },
      ],
      {},
    );
  },
  async down(queryInterface) {
    await queryInterface.bulkDelete("comments", null, {});
    await queryInterface.bulkDelete("characters", null, {});
  },
};
